### PR TITLE
Update readmes to reference coursierapi

### LINKED ISSUE #1003: Cousier update changed API
I just noticed that some of the docs need updating.

This section here no longer work in v1.7.1 due to (I assume) Coursier updates.

```
Including repositories which need authentication:

import coursier.core.Authentication, coursier.MavenRepository

interp.repositories() ++= Seq(MavenRepository(
  "https://nexus.corp.com/content/repositories/releases",
  authentication = Some(Authentication("user", "pass"))
))
```

It results in the following:

```
cmd1.sc:1: not found: value coursier
import coursier.core.Authentication, coursier.MavenRepository
       ^
cmd1.sc:1: not found: value coursier
import coursier.core.Authentication, coursier.MavenRepository
                                     ^
Compilation Failed
```

Instead, this exists:

```
@ import coursierapi.MavenRepository 
import coursierapi.MavenRepository
```

### PR DESCRIPTION
**Pull request by jabrouwer82**
Fixes #1003 by updating readme to reflect changes from #990

### CODE REVIEW

**Comment by jabrouwer82** [comment]
Re: appveyor, it looks like it's set to use a relatively old version of mill (0.4.1) but build.sc can't run anything older than 0.5.1, I (extremely naively) think I could just bump the MILL_URL in appveyor.yml to 0.5.1 or 0.5.7 (the default in the mill shell script), do y'all want me to give that go in this pr?

**Comment by alexarchambault** [comment]
CI is green now. Merging, thanks!
