### ISSUE TITLE
Two compilation errors when using Scala 2.10.4

### ISSUE THREAD

**Issue by deanwampler** [lihaoyi/Ammonite#20]
Attempting to build with 2.10.4 (for use with Spark projects):

```
[info] Compiling 11 Scala sources to /Users/deanwampler/projects/scala/Ammonite/core/target/scala-2.10/classes...
[error] /Users/deanwampler/projects/scala/Ammonite/core/src/main/scala/ammonite/pprint/PPrint.scala:219: object blackbox is not a member of package scala.reflect.macros
[error]     def FinalRepr[T: c.WeakTypeTag](c: scala.reflect.macros.blackbox.Context) = c.Expr[PPrint[T]] {
[error]                                                             ^
[error] /Users/deanwampler/projects/scala/Ammonite/core/src/main/scala/ammonite/ops/Tools.scala:19: value quote is not a member of object scala.util.matching.Regex
[error]       Regex.apply(scala.util.matching.Regex.quote(t).r, s)
[error]                                             ^
[error] two errors found
```

Once fixed, would it be possible to publish 2.10 artifacts?

**Comment by lihaoyi** [comment]
Sure! Want to send a PR? The second should be a pretty straightforward replacement, while the first may need some mucking around with macros to make it work

**Comment by deanwampler** [comment]
I'll try!

**Comment by lihaoyi** [comment]
@deanwampler Thanks to @alexarchambault 2.10 has been supported in the latest version 0.2.6 and we'll try to maintain it going forward
