### ISSUE TITLE
Regression when upgrading from 1.0.2 to 1.1.0

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [lihaoyi/Ammonite#794]
I have this script:
```
#!/usr/bin/env amm

// Se ha realizado desde SBT:
//   cmd "chmod +r /home/ema/escuchador/trabajo/tramas.db" root escuchadores
import java.net.InetAddress

import ammonite.ops.{read ⇒ lee, _}, ImplicitWd._
import upickle.default._

import scala.util.{Try, Success}
import org.apache.http._
import org.apache.http.auth.{AuthScope, UsernamePasswordCredentials}
import org.apache.http.impl.client.{BasicAuthCache, BasicCredentialsProvider, HttpClients}
import org.apache.http.impl.auth.DigestScheme
import org.apache.http.client.protocol.HttpClientContext
import org.apache.http.client.methods.HttpGet
import org.apache.http.util.EntityUtils
import $ivy.`org.apache.httpcomponents:httpclient:4.5.2`
import $file.omd, omd._, Estado._

/** Ej. de respuesta:
	    `{"Hora": "17:33:03", "Bytes enviados/min": 21670, "Conectados": 74, "Bytes recibidos/min": 234812, "Tramas/min": 1297, "ErroresPost/min": 0, "Post/min": 289}` */
case class Datos(@key("Bytes enviados/min") enviados: Int,
				 Conectados: Int,
				 @key("Bytes recibidos/min") recibidos: Int,
				 @key("Tramas/min") tramas: Int,
				 @key("ErroresPost/min") errores: Int,
				 @key("Post/min") post: Int)

@main
def ini(avisoTramas: Int = 0, critTramas: Int = 0, avisoErrores: Int = 0, critErrores: Int = 0, avisoAcumulados: Int = 0, critAcumulados: Int = 0) {
	System.setProperty("org.apache.commons.logging.Log", "org.apache.commons.logging.impl.NoOpLog")
	val dest = new HttpHost("localhost", 8001, "http")
	val cred = new BasicCredentialsProvider()
	cred.setCredentials(new AuthScope(dest.getHostName, dest.getPort), new UsernamePasswordCredentials("ismael", "rdsmaps"))
	val cli = HttpClients.custom().setDefaultCredentialsProvider(cred).build()
	val ctx = HttpClientContext.create()
	val dig = new DigestScheme()
	dig.overrideParamter("realm", InetAddress.getLocalHost.getHostName)
	val cache = new BasicAuthCache()
	cache.put(dest, dig)
	ctx.setAuthCache(cache)
	val tramasDb = root/'home/'ema/'escuchador/'trabajo/"tramas.db"
	val res = try {
		val urlBase = s"http://${dest.getHostName}:${dest.getPort}/"
		val resp = cli.execute(dest, new HttpGet(s"$urlBase/estadisticas?minutos=5"), ctx)
		if (resp.getStatusLine.getStatusCode == 200) {
			val d = read[Datos](EntityUtils.toString(resp.getEntity))
			val acumulados = Try {((stat! tramasDb).size / 1024 / 1024).toInt }.getOrElse(0)
			def chequea(etiq: String, aviso: Int, critico: Int, valor: Int) = {
				if (critico != 0 && valor > critico)
					Res(CRITICO, s"$etiq $valor supera $critico")
				else if (aviso != 0 && valor > aviso)
					Res(AVISO, s"$etiq $valor supera $aviso")
				else
					Res.OK
			}
			def chequeaMenos(etiq: String, aviso: Int, critico: Int, valor: Int) = {
				if (critico != 0 && valor < critico)
					Res(CRITICO, s"$etiq $valor menor que $critico")
				else if (aviso != 0 && valor < aviso)
					Res(AVISO, s"$etiq $valor menor que $aviso")
				else
					Res.OK
			}
			val resp2 = cli.execute(dest, new HttpGet(s"$urlBase/menu"), ctx)
			val estControl = if (resp2.getStatusLine.getStatusCode == 200) {
				val d2 = EntityUtils.toString(resp2.getEntity)
				if (d2.indexOf("Area de datos de control: ma_prc_gps") >= 0)
					Res(OK, s"Conectado al área control")
				else
					Res(CRITICO, "No conectado al área control")
			} else {
				Res(DESCONOCIDO, s"No podido mirar si conectado al área control: ${resp2.getStatusLine.getReasonPhrase}")
			}
			val c = Seq(
				chequeaMenos("Tramas/min", avisoTramas, critTramas, d.tramas),
				chequea("Errores post/min", avisoErrores, critErrores, d.errores),
				chequea("Datos acumulados", avisoAcumulados, critAcumulados, acumulados),
				estControl,
				Res(OK, "",
					"Enviado" → d.enviados,
					"Recibido" → d.recibidos,
					"Tramas" → d.tramas,
					"Errores post" → d.errores,
					"Post" → d.post,
					"Datos acumulados" → acumulados,
					"Conec.area ctrl" → (if (estControl.est == OK) 1 else 0))
			) /*++
			Seq("gpsdat", "gpsimg", "gpstra").map { t ⇒
				// Para que tenga exito debe ejecutarse como usuario ema
				Try {%%('sqlite3, tramasDb, s"select count(*) from $t;").out.string.trim.toLong} match {
					case Success(n) ⇒ Res(OK, "", t → n)
					case _ 			⇒ Res(CRITICO, s"No se puede determinar filas que tiene tabla $t")
				}
			}*/

			c.reduce(_+_)
		} else {
			Res(DESCONOCIDO, s"Error HTTP ${resp.getStatusLine.getStatusCode} ${resp.getStatusLine.getReasonPhrase}")
		}
	} catch { case ex: Throwable ⇒
		new Res(ex)
	}
	res.notifica()
}
```

It compiles ok with version 1.0.2.
When using version 1.1.0, it provides this compile errors:
```
chequea-escuchador.sc:3: not found: type key
// Se ha realizado desde SBT:
          ^
chequea-escuchador.sc:4: not found: type key
//   cmd "chmod +r /home/ema/escuchador/trabajo/tramas.db" root escuchadores
                                                 ^
chequea-escuchador.sc:5: not found: type key
import java.net.InetAddress
                     ^
chequea-escuchador.sc:7: not found: type key
import ammonite.ops.{read ⇒ lee, _}, ImplicitWd._
                             ^
chequea-escuchador.sc:8: not found: type key
import upickle.default._
                      ^
chequea-escuchador.sc:48: could not find implicit value for evidence parameter of type upickle.default.Reader[ammonite.$file.libexec.chequea-escuchador.Datos]
			val d = read[Datos](EntityUtils.toString(resp.getEntity))
                                           ^
Compilation Failed
```

After importing:
```
import upickle.key
```
all errors disappear with the exception of the last one, and I don't know how to solve it.

I think that built-in upickle has been upgraded and has different behavior.

How can I solve the last error?

```
could not find implicit value for evidence parameter of type upickle.default.Reader[ammonite.$file.libexec.chequea-escuchador.Datos]
```

**Comment by DavidPerezIngeniero** [comment]
Confirmed that this solution works ok!
