### ISSUE TITLE
ls! gives no output

### ISSUE THREAD

**Issue by cvogt** [lihaoyi/Ammonite#22]
```
@ import ammonite.all._
import ammonite.all._
@
@ // Get the current working directory
@ val wd = processWorkingDir
wd: ammonite.ops.Path = root/'Users/'chris/'bin/"ammonite-scala-repl"
@
@ // Make a folder named "folder1"
@ mkdir! wd/'folder1
res2: Unit = ()
@
@ // List the current directory
@ ls! wd

@
```

Here is my build.sbt
```

libraryDependencies += "com.lihaoyi" %% "ammonite-repl" % "0.2.0" % "test"

initialCommands in console := "ammonite.repl.Repl.main(null)"

name := "Ammonite Repl"

scalaVersion := "2.11.4"

```

**Comment by lihaoyi** [comment]
Odd, it should print *something* even if Seq().

**Comment by lihaoyi** [comment]
@cvogt do you want to try this out in master? Just download the repo and run `repl/run` to open up a shell...

**Comment by cvogt** [comment]
For 60f48df5811306d4c3e374af8ee8d25457c05b72 I am getting
```
[warn] there were four deprecation warnings; re-run with -deprecation for details
[warn] there were two feature warnings; re-run with -feature for details
[warn] two warnings found
[info] Compiling 7 Scala sources to /Users/chris/playground/Ammonite/ops/target/scala-2.11/classes...
[warn] /Users/chris/playground/Ammonite/ops/src/main/scala/ammonite/ops/FileOps.scala:12: imported `up' is permanently hidden by definition of value up in trait RelPathStuff
[warn] import RelPath.up
[warn]                ^
[warn] /Users/chris/playground/Ammonite/ops/src/main/scala/ammonite/ops/Path.scala:8: imported `up' is permanently hidden by definition of value up in trait RelPathStuff
[warn] import RelPath.up
[warn]                ^
[error] /Users/chris/playground/Ammonite/ops/src/main/scala/ammonite/ops/FileOps.scala:174: value list is not a member of object java.nio.file.Files
[error]     Files.list(arg.nio).iterator().asScala.map(x => Path(x))
[error]           ^
[warn] two warnings found
[error] one error found
[error] (ops/compile:compile) Compilation failed
[error] Total time: 18 s, completed 03.03.2015 10:46:55
```

**Comment by cvogt** [comment]
Java 7/8 problem or something?
```
java -version
java version "1.7.0_55"
Java(TM) SE Runtime Environment (build 1.7.0_55-b13)
Java HotSpot(TM) 64-Bit Server VM (build 24.55-b03, mixed mode)
```

**Comment by paulp** [comment]
Yes it doesn't compile with java 7.

**Comment by lihaoyi** [comment]
yeah that's probably it. Given that Java 7 is going to be unsupported in 2 months, could I ask you to upgrade? =P I'll put a note somewhere in the readme saying JAVA 8 ONLY

https://www.java.com/en/download/faq/java_7.xml

**Comment by lihaoyi** [comment]
Should work on Java 7 as of `0.2.6`

**Comment by cvogt** [comment]
thx!
