### ISSUE TITLE
0.7.5 predef.sc compilation error with `...}}\ndef anything . . . `

### ISSUE THREAD

**Issue by emanresusername** [lihaoyi/Ammonite#453]
predef.sc
```scala
{{
}}
def breaks = "in 0.7.5"
```
```text
LoadedPredef.sc:64: ';' expected but 'def' found.
}def breaks = "in 0.7.5"
 ^
java.lang.RuntimeException: Error during Predef: Compilation Failed
  at ammonite.runtime.Interpreter$$anonfun$10.apply(Interpreter.scala:134)
  at ammonite.runtime.Interpreter$$anonfun$10.apply(Interpreter.scala:118)
  at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:733)
  at scala.collection.immutable.List.foreach(List.scala:381)
  at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:732)
  at ammonite.runtime.Interpreter.<init>(Interpreter.scala:118)
  at ammonite.repl.Repl.<init>(Repl.scala:43)
  at ammonite.Main.instantiateRepl(Main.scala:61)
  at ammonite.Main.run(Main.scala:107)
  ... 39 elided
```
works fine in 0.7.4
in the mean time, i worked around just putting the `{{}}` stuff at the end 
```scala
def works = "fine if before"
{{
}}
```

**Comment by lihaoyi** [comment]
Thanks for the report!

**Comment by lihaoyi** [comment]
@emanresusername would one solution be to convert the `{{}}` stuff to just `{}` stuff?

**Comment by emanresusername** [comment]
@lihaoyi yeah, so in my case i was using `{{}}` limit the scope of some variables i was only using in my prompt
```scala
{{
// don't want any of the defs in the repl session
  def current_branch = {
    scala.util.Try {
      ((%%git('branch)).out.lines.filter(grep!("""\*""".r))).head.substring(2)
    }.toOption
  }

  def hostname = {
    (%%hostname).out.lines.head
  }

  def whoami = {
    (%%whoami).out.lines.head
  }

  def date = {
    (%%date("-Is")).out.lines.head.split("-").dropRight(1).mkString("-")
  }

  repl.prompt.bind(
    Seq(
      Option(s"$whoami@$hostname:${wd.toString}[$date]"),
      current_branch.map(branch => {
        s"<$branch>"
      }),
      Option("\nᕕ( ᐛ )ᕗ ")
    ).flatten.mkString
  )
}}
```
with just `{}` all those variables leak into the repl session . . . but even though i liked the `0.7.4` behavior, this really isn't a __HUGE__ issue either way. after all, everything breaks SOMEbody's workflow 😅 
[![](https://imgs.xkcd.com/comics/workflow.png)](https://xkcd.com/1172/)
maybe there's just a better way to do this altogether?

**Comment by lihaoyi** [comment]
`5ad48f3` should make `{}` work in scripts to avoid leakage, and `{{}}` should be the same as `{}`, both behaving the same as "normal" Scala. The "unwrapping" behavior on `{}` will then be reserved for the interactive REPL.

FWIW, just using `private` within your predef/scripts scripts should *also* avoid leakage :P

```scala
Welcome to the Ammonite Repl 0.7.5
(Scala 2.11.8 Java 1.8.0_102)
haoyi-Ammonite@ %cat "foo.sc"
private[this] val x = 1
val y = x + 1

haoyi-Ammonite@ import $file.foo
import $file.$
haoyi-Ammonite@ foo.x
cmd2.sc:1: value x is not a member of object $file.foo
val res2 = foo.x
               ^
Compilation Failed
haoyi-Ammonite@ foo.y
res2: Int = 2
```

**Comment by emanresusername** [comment]
ahh `private`, that is definitely better . . . just don't disable spacebar heating!! ![](https://dujrsrsgsd3nh.cloudfront.net/img/emoticons/lol-1414023491.png)

**Comment by lihaoyi** [comment]
Fixed in version `COMMIT-5ad48f3` http://www.lihaoyi.com/Ammonite/#UnstableVersions
