### ISSUE TITLE
Cousier update changed API

### ISSUE THREAD

**Issue by NeQuissimus** [lihaoyi/Ammonite#1003]
I just noticed that some of the docs need updating.

This section here no longer work in v1.7.1 due to (I assume) Coursier updates.

```
Including repositories which need authentication:

import coursier.core.Authentication, coursier.MavenRepository

interp.repositories() ++= Seq(MavenRepository(
  "https://nexus.corp.com/content/repositories/releases",
  authentication = Some(Authentication("user", "pass"))
))
```

It results in the following:

```
cmd1.sc:1: not found: value coursier
import coursier.core.Authentication, coursier.MavenRepository
       ^
cmd1.sc:1: not found: value coursier
import coursier.core.Authentication, coursier.MavenRepository
                                     ^
Compilation Failed
```

Instead, this exists:

```
@ import coursierapi.MavenRepository 
import coursierapi.MavenRepository
```

**Comment by marcoy** [comment]
We have a script that requires access to our private nexus repo. Here is a way to get it working again.

```
import coursierapi.MavenRepository
import coursierapi.Credentials

val username = ???
val password = ???
val credentials = Credentials.of(username, password)
val maven = MavenRepository.of("your-nexus-url").withCredentials(credentials)

interp.repositories() ++= List(maven)

// ..... 8< .....
```

**Comment by DavidPerezIngeniero** [comment]
With Ammonite 1.7.4 is getting worse:

```
 value ++= is not a member of List[coursierapi.Repository]
```

**Comment by danslapman** [comment]
@DavidPerezIngeniero now the correct pattern is
```
import coursierapi.MavenRepository

interp.repositories.update(
  interp.repositories() ::: List(MavenRepository.of("https://some_repo"))
)
```
